### ISSUE TITLE
After installing the plugin on Mac M2 IntelliJ no longer starts

### ISSUE THREAD

**Issue by eyufit** [kdbinsidebrains/sample#1]
Stacktrace below:

![IMG_1020](https://github.com/kdbinsidebrains/sample/assets/118200380/67d073d1-c2f3-4cda-9429-84797fef9dba)

**Comment by eyufit** [comment]
2023.2.3 Community Addition

**Comment by eyufit** [comment]
This should have been raised under the plugin, but can’t see how to move it :(

**Comment by smklimenko** [comment]
Sorry, I don't have any Mac and have no plan to get any in the future so can't trace the issue.

What I can advise - physically remove the plugin file **KdbInsideBrains.zip** from plugins folder described here: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

```
Syntax
~/Library/Application Support/JetBrains/<product><version>/plugins

Example
~/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins
```

After that you should be able to start the IDEA but I'm afraid you can't use the plugin.
